[package]
name = "mini_guardian"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
colored = "3.0.0"
regex = "1.12.2"
serde = "1.0.228"
serde_json = "1.0.145"
walkdir = "2.5.0"
